spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:13306/sample?socketTimeout=30000&connectTimeout=30000&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=utf8&allowMultiQueries=true
    username: bkjeon
    password: wjsqhdrms
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always