version: '3.7'
services:
  db:
    image: mysql:8.0
    container_name: mysql01
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wjsqhdrms
      MYSQL_DATABASE: sample
      MYSQL_USER: bkjeon
      MYSQL_PASSWORD: wjsqhdrms
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis01
    ports:
      - "16379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local