version: '3.6'
services:
  db:
    image: mysql:8.0
    container_name: mysql01
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wjsqhdrms
      MYSQL_DATABASE: sample
      MYSQL_USER: bkjeon
      MYSQL_PASSWORD: wjsqhdrms
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge