spring:
  profiles:
    active: local_dev
  application:
    name: bkjeon-mybatis-codebase

mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
  type-aliases-package: com.example.bkjeon.mapper
  configuration:
    cacheEnabled: false
    useGeneratedKeys: true
    defaultExecutorType: REUSE
    aggressiveLazyLoading: false
    default-statement-timeout: 30
    map-underscore-to-camel-case: true

server:
  port: 9090
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html

# circuitbreaker
resilience4j:
  retry:
    configs:
      default:
        registerHealthIndicator: true # actuator 정보 노출을 위한 설정
        maxRetryAttempts: 5 # 최대 재시도 수
        waitDuration: 5000  # 재시도 사이에 고정된 시간 [ms]
        #retryExceptions:
        #  - org.springframework.web.client.HttpServerErrorException
        #  - java.io.IOException
        #ignoreExceptions:
        #  - java.util.NoSuchElementException
    instances:
      retry-test-3000: # retry name
        baseConfig: default # 기본 config 지정 (Ex-retry.configs.{default})
        waitDuration: 3000
      retry-db-select-4000:
        baseConfig: default
        waitDuration: 4000
      retry-db-select-5000:
        baseConfig: default
        waitDuration: 5000
  circuitbreaker:
    configs:
      default:  # 기본 config 명
        registerHealthIndicator: true # actuator 정보 노출을 위한 설정
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 10  # 최소한 호출을 10번을 기록해야 실패 비율을 계산할 수 있다.
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 10s  # 서킷의 상태가 Open 에서 Half-open 으로 변경되기전에 Circuit Break가 기다리는 시간 [s]
    instances:
      circuit-test-70000: # circuitbreaker name
        baseConfig: default # 기본 config 지정 (Ex-circuitbreaker.configs.{default})
        slowCallDurationThreshold: 70000 # 응답시간이 느린것으로 판단할 기준 시간 [ms]
      circuit-db-select-200:
        baseConfig: default
        slowCallDurationThreshold: 200
      circuit-db-select-300:
        baseConfig: default
        slowCallDurationThreshold: 300

# actuator
management:
  endpoint:
    health:
      show-details: always
      enabled: true
    heapdump:
      enabled: true
    caches:
      enabled: false
    beans:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health, heapdump, info, metrics, prometheus, retries, applicationLibInfo, env, git, build  # actuator 노출 원하는 정보 선택
        exclude: beans
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    build:
      enabled: true
  health:
    circuitbreakers:
      enabled: true # circuitbreakers 정보 노출
    retryevents:
      enabled: true # retryevents 정보 노출

info: # /actuator/info 정보가 표시되는것을 볼 수 있다.
  app-info:
    projectName: ${ext.projectName}
    group: ${group}
    version: ${version}
    javaVersion: ${sourceCompatibility}

# SpEL
spel:
  value: 100