spring:
  profiles: local_dev
  boot:
    admin:
      client:
        instance:
          service-url: http://127.0.0.1:9090/api
          name: bkjeon-api
        url:
          - http://127.0.0.1:9091
        auto-registration: true
  sleuth:
    sampler:
      probability: 1.0
    enabled: false
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: false
  oracle:
    datasource:
      jdbcUrl: jdbc:oracle:thin:@127.0.0.1:1521/xe
      username: root
      password: ENC(+ZVnlLxUPZ+UErIx+qIr+UC7PsbH8JPI)
      driver-class-name: oracle.jdbc.driver.OracleDriver
  mysql:
    datasource:
      jdbcUrl: jdbc:log4jdbc:mysql://127.0.0.1:3306/bkjeon?socketTimeout=30000&connectTimeout=30000&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=utf8
      username: root
      password: ENC(+ZVnlLxUPZ+UErIx+qIr+UC7PsbH8JPI)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  redis:
    base:
      host: localhost
      port: 6379
      database: 0
      timeout: 50
      replicas:
        - host: localhost
          port: 6479
          database: 0
          timeout: 50
        - host: localhost
          port: 6579
          database: 0
          timeout: 50

kafka:
  brokers: 192.168.0.203:9092,192.168.0.204:9092,192.168.0.205:9092

elasticsearch:
  hosts: 127.0.0.1:9200
  username: elastic
  password: elastic

external:
  api:
    user:
      url: https://jsonplaceholder.typicode.com
      token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ7XCJwb3NpdERlcHRJZFwiOjMsXCJkbW5DZFwiOlwiRUxUXCIsXCJhcGlrZXlJZFwiOlwiRUxUXzE1NTY1MjM