spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}
  main:
    web-application-type: none

mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
  type-aliases-package: com.example.bkjeon.mapper
  configuration:
    cacheEnabled: false
    useGeneratedKeys: true
    defaultExecutorType: REUSE
    aggressiveLazyLoading: false
    default-statement-timeout: 30
    map-underscore-to-camel-case: true

info: # /actuator/info 정보가 표시되는것을 볼 수 있다.
  app-info:
    projectName: ${ext.projectName}
    group: ${group}
    version: ${version}
    javaVersion: ${sourceCompatibility}

# Local Env (Mysql DB)
---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bkjeon?socketTimeout=30000&connectTimeout=30000&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: ENC(+ZVnlLxUPZ+UErIx+qIr+UC7PsbH8JPI)
    driver-class-name: com.mysql.cj.jdbc.Driver

chromedriver:
  id: webdriver.chrome.driver
  path: ./file/chromedriver.exe

logging:
  level:
    org:
      springframework:
        batch: DEBUG

server:
  port: 9091

# Dev Env
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study?socketTimeout=30000&connectTimeout=30000&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=utf8&allowMultiQueries=true
    username: bkjeon
    password: ENC(+ZVnlLxUPZ+UErIx+qIr+UC7PsbH8JPI)
    driver-class-name: com.mysql.cj.jdbc.Driver

chromedriver:
  id: webdriver.chrome.driver
  path: /home/bkjeon/app/chromedriver/chromedriver

logging:
  level:
    org:
      springframework:
        batch: INFO

server:
  port: 9091

# Production Env
---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study?socketTimeout=30000&connectTimeout=30000&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=utf8&allowMultiQueries=true
    username: bkjeon
    password: ENC(+ZVnlLxUPZ+UErIx+qIr+UC7PsbH8JPI)
    driver-class-name: com.mysql.cj.jdbc.Driver

chromedriver:
  id: webdriver.chrome.driver
  path: /home/bkjeon/app/chromedriver/chromedriver

logging:
  level:
    org:
      springframework:
        batch: INFO

server:
  port: 9091
