spring:
  profiles:
    active: local

server:
  port: 9000

# Local Env (H2 DB)
---

spring:
  profiles: local-h2
  datasource:
    jdbcUrl: jdbc:h2:mem:testdb
    username: sa
    driverClassName: org.h2.Driver
    data: classpath:sql/data-h2.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

decorator:
  datasource:
    p6spy:
      enable-logging: true

# Dev Env (Mysql DB)
---

spring:
  profiles: local-db
  datasource:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/bkjeon_jpa?socketTimeout=30000&connectTimeout=30000&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=utf8
    username: bkjeon
    password: wjsqhdrms
    driverClassName: com.mysql.cj.jdbc.Driver
    data: classpath:sql/data-h2.sql
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop

decorator:
  datasource:
    p6spy:
      enable-logging: true

# Dev Env
---

spring:
  profiles: dev
  datasource:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/bkjeon?socketTimeout=30000&connectTimeout=30000&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=utf8
    username: bkjeon
    password: wjsqhdrms
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate

# Production Env
---

spring:
  profiles: prod
  datasource:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/bkjeon?socketTimeout=30000&connectTimeout=30000&serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=utf8
    username: bkjeon
    password: wjsqhdrms
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate